name: Sophia McLees
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000000'
    - '#a5a5a5'
    - '#3e3e3e'
    - '#5c5c5c'
  brandStrength: 0.6875
  lightness: 0.285034614847973
  saturation: 0.36999258934520185
  rhythmicContrast: 0.8152703673113137
purpose: []
